import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
        style={{
          backgroundColor:"lightblue",
          padding:"lrem",
        }}>
          <p>Header</p>
        </header>
          <ReduxProvider>{children}</ReduxProvider>
        <footer 
        style={{
          backgroundColor:"ghostwhite",
          color: "red",
          padding:"lrem",
        }}>
          <p> footer</p>
        </footer>
        </body>
    </html>
  );
}
